name: Cron Jobs [Mon-Fri]
on:
  schedule:
    - cron: '0 18 * * 1-5'

jobs:
  reporting:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .
        
      - name: Report generation
        env:
          PORTFOLIO_XLXS: ${{ secrets.PORTFOLIO_XLXS }}
        run: |
          data <- lares::stocks_file(Sys.getenv("PORTFOLIO_XLXS"))
          rep  <- lares::stocks_obj(data)
          lares::stocks_report(rep, dir = tempdir())
        shell: Rscript {0}
      
      - name: Send report
        env:
          MAILGUN_URL: ${{ secrets.MAILGUN_URL }}
          MAILGUN_TOKEN: ${{ secrets.MAILGUN_TOKEN }}
        run: |
          report <- paste0(tempdir(), "/stocksReport.html")
          lares::mailSend(attachment = report, creds = list(
            url = Sys.getenv("MAILGUN_URL"), 
            api = Sys.getenv("MAILGUN_TOKEN"))
        shell: Rscript {0}
